#  Sonatype Nexus (TM) Open Source Version
#  Copyright (c) 2020-present Sonatype, Inc.
#  All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
#
#  Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
#  of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
#  Eclipse Foundation. All other trademarks are the property of their respective owners.
version: 2.1
orbs:
  circleci-nancy-orb: sonatype-nexus-community/circleci-nancy-orb@<<pipeline.parameters.dev-orb-version>>

# Pipeline parameters
parameters:
  dev-orb-version:
    type: string
    # during active development of this orb, the default version below should be: "dev:alpha"
    #default: "dev:alpha"
    default: "0.0.22"

jobs:
  job-nancy-scan:
    executor: circleci-nancy-orb/golang-executor
    steps:
      - circleci-nancy-orb/install-nancy
      - circleci-nancy-orb/run-nancy

workflows:
  main:
    jobs:
      - job-nancy-scan
