#  Sonatype Nexus (TM) Open Source Version
#  Copyright (c) 2020-present Sonatype, Inc.
#  All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
#
#  Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
#  of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
#  Eclipse Foundation. All other trademarks are the property of their respective owners.
version: 2.1
orbs:
  # during active development of the orb, the version below should be: "dev:alpha"
  circleci-nancy-orb: sonatype-nexus-community/circleci-nancy-orb@dev:alpha

jobs:
  job-nancy-scan-latest:
    executor: circleci-nancy-orb/golang-executor
    steps:
      - checkout
      - circleci-nancy-orb/install-nancy
      - circleci-nancy-orb/run-nancy

  job-nancy-scan-specific-version:
    executor: circleci-nancy-orb/golang-executor
    steps:
      - checkout
      - circleci-nancy-orb/install-nancy:
          nancy-version: "v1.0.14"
      - circleci-nancy-orb/run-nancy

workflows:
  main:
    jobs:
      - job-nancy-scan-latest
      - job-nancy-scan-specific-version

  build_nightly:
    triggers:
      - schedule:
          cron: "15 20 * * *"
          filters:
            branches:
              only: master
    jobs:
      - job-nancy-scan-latest
      - job-nancy-scan-specific-version
